### ISSUE TITLE
Fix category/post-type seeding

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#638]
> **luap42 🍭**: @ArtOfCode- that is sonething for you as I don't know how to properly fix it: the rep per post type and category update broke category seeding as that depends on the old data model.
>
> <sub>&mdash; [Discord](https://discord.com/channels/634104110131445811/752215864354537524/878335134661746698)</sub>

Needs fixing, here's a reminder for me to do it.

**Comment by Trilarion** [comment]
Might this be related to [Error undefined method `has_tags' or `id' for nil:NilClass during rails db:seed](https://collab.codidact.org/posts/285521)?

**Comment by Trilarion** [comment]
After confirmation in#759 by somebody else, let me summarize:

The database seed script doesn't run without errors. The question post type cannot be created. New setups can't have questions at the moment.

That is kind of critical and should maybe get a high priority.

**Comment by Trilarion** [comment]
I think I got a bit closer. The reason is

    validates :answer_type_id, presence: true, if: :has_answers?

in post_type.rb which requires an answer_type_id if a post type has answers (introduced in 8f6462658b27df919c4a3f1b898ec429b3d21598).  The seed for questions (the only post type that has answers) in post_types.yml doesn't have an answer_type_id. I tried to add something like

    answer_type_id: <%= Answer.post_type_id %>

to post_types.yml, but that didn't work. How do I reference to something that is not yet existing during seeding?

**Comment by Trilarion** [comment]
I think I got it now:

    answer_type_id: <%= PostType['Answer'].id %>

seems to do the job. Will test it more and then submit PR if working.

**Comment by Trilarion** [comment]
Hmm, that only worked because PostType['Answer'] was there from a previous run of db:seed. This is fragile. It should all run through with a single execution of db:seed. I may need to split post_types.yml into two files where Answer is in the one that is processed first and Question (that depends on Answer) in the second.

**Comment by Trilarion** [comment]
I think I understand the issue pretty well by now. Questions as post types have answers and as such must know what type of answers they can accept in case there are more than a single type of answers. That means that the post type answer must be known before questions as a post type can be created. However, in the current seed script the parameters are all imported from yaml and initialized at once. Either we do that ERB.new().result(binding) differently that it iterates over each entry instead of doing all at once or we simply put the post types seeds into multiple files or something else to that effect.

It's not even the only problem with the seeds. There are others but not as severe ones.

**Comment by Trilarion** [comment]
Solution in #775 (work in progress)

**Comment by Taeir** [comment]
I fixed all seeding issues in #822.
